### ISSUE TITLE
Newly added icon not shown

### ISSUE THREAD

**Issue by washbin** [TheLearneer/api-party#236]
**Describe the bug**
The logo of newly added api is not being displayed despite following all the steps mentioned to add a new api. I am unsure but I presume it is due to addition of a new category, although the error in terminal suggests category-icon error only, I am unable to see the actual api icon as well.

**To Reproduce**
- add a new api under a new category

**Expected behavior**
Expected to see an icon for the newly added api

**Screenshots**
![error](https://user-images.githubusercontent.com/76929116/194030250-5a9b6480-baf7-4e17-9720-cbe89f644d24.png)
![image](https://user-images.githubusercontent.com/76929116/194030154-852aa38a-60da-4e7d-8773-500768c8f760.png)

**Additional context**
I saw the problem in my local build, don't know if this affect some other build or if this is some minor stupidity I am not catching yet, Nevertheless, I have decided to open a pull request with all the changes leading to the issue

**Comment by TheLearneer** [comment]
The usage of icon is wrong, Please always refer to `CONTRIBUTING.md` 🙇
