### ISSUE TITLE
Add missing category icons

### ISSUE THREAD

**Issue by TheLearneer** [TheLearneer/api-party#241]
**Is your feature request related to a problem? Please describe.**
After some recent contributions we have few categories that don't have any icons at all.
The categories are:
- Books
- Currency
- Foods

**Describe the solution you'd like**
Add a icons for all these categories that are missing

**Describe alternatives you've considered**
N/A

**Additional context**
Before opening a pull request for this task, I would love if you can propose the icons that would be best fit for the website. (i.e. share the image of the icons)

**Comment by beheradibas** [comment]
Hi @TheLearneer 

Please have a look at these icons :
Books : https://alpercon.github.io/Termodinamica/images/open-book.png, https://www.pngfind.com/pngs/m/344-3441162_classroom-icon-stack-of-books-png-transparent-png.png
Currency : https://i.stack.imgur.com/1vUdd.png , https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Money_bolivar_icon.svg/120px-Money_bolivar_icon.svg.png
Food : http://icons.iconarchive.com/icons/google/noto-emoji-food-drink/1024/32393-pot-of-food-icon.png, https://i0.wp.com/cdn.icon-icons.com/icons2/1864/PNG/512/iconfinder-healthcare-and-medicalorganicvegansaladhealthy-foodavocadodietvegetarianfoodfruit-4394779_119506.png

Please assign me the issue if these icons are meeting the requirements, also I am open to search for more icons but if you have any guideline on how they should look it would help to find icons faster.

**Comment by TheLearneer** [comment]
Hi @beheradibas 👋 
Thank you for your interest in the project.

First thing first, All the current category icons are SVG files, so the newly added icons should be SVG as well.
I am open to any icons that you can come up with.

I am assigning it to you as well.

**Comment by beheradibas** [comment]
Sure, I will attach SVG icons and make a PR.

**Comment by beheradibas** [comment]
Here are the images in SVG format I am wiling to add 
![books](https://user-images.githubusercontent.com/46717953/194739797-d3f749ef-c16b-4e1a-af9a-8f00448a43c5.svg)
![currency](https://user-images.githubusercontent.com/46717953/194739800-7419c9b9-44ae-47ab-b12d-3d80c431f34c.svg)
![food](https://user-images.githubusercontent.com/46717953/194739803-459de8ce-9c04-4fe7-b7bc-1b2e14349e6d.svg)

Will that be okay

**Comment by TheLearneer** [comment]
@beheradibas The food SVG is just perfect.

For the books SVG, what if we use one of the following:
- https://freesvg.org/books
- https://freesvg.org/stack-of-two-books-vector-graphics

Also, for currency, what if we use https://upload.wikimedia.org/wikipedia/commons/8/8a/Icons8_flat_currency_exchange.svg
