### ISSUE TITLE
✍️ Write an article about API authentication

### ISSUE THREAD

**Issue by TheLearneer** [TheLearneer/api-party#247]
## Is your feature request related to a problem? Please describe.
Write a detailed article about API authentication.

## Describe the solution you'd like
Explain about:
- Why is authentication necessary
- API key, OAuth
- rate limiting, ip whitelisting
- Authentication vs Authorization

## Describe alternatives you've considered
N/A

## Additional context
Create a file at https://github.com/TheLearneer/api-party/tree/main/src/content/wiki
Name it `2.api-authentication` and write the content inside it

Please check https://github.com/TheLearneer/api-party/blob/main/src/content/wiki/1.what-is-api.md to know about some structure that needs to be followed

**Comment by varadtote** [comment]
Assign this issue to me.
I write article on this topic considering all the points you mentioned.

**Comment by TheLearneer** [comment]
Assigning it to you @varadtote 
Make sure to write an awesome article 🙌

**Comment by shahGnp** [comment]
Hey, can I work on this?

**Comment by TheLearneer** [comment]
Hi @shahGnp there already is an PR opened for the issue.
I am just waiting for the author to resolve it 🙏
