### ISSUE TITLE
✍️ Write an article about API consumption

### ISSUE THREAD

**Issue by TheLearneer** [TheLearneer/api-party#248]
## Is your feature request related to a problem? Please describe.
Write a detailed article about consuming API.

## Describe the solution you'd like
Explain about:
- Ways to consume API (mobile apps, web apps, scripts, tools)
- Give example of APIs being consumed in mobile apps, web apps, script
- List out different tools that can be used to consume APIs (Postman, Hoppscotch etc)

## Describe alternatives you've considered
N/A

## Additional context
Create a file at https://github.com/TheLearneer/api-party/tree/main/src/content/wiki
Name it `3.usage-of-api` and write the content inside it

Please check https://github.com/TheLearneer/api-party/blob/main/src/content/wiki/1.what-is-api.md to know about some structure that needs to be followed

**Comment by darkbits018** [comment]
can i work on this ??

**Comment by TheLearneer** [comment]
Yeah sure @darkbits018 assigning it to you 🙏

**Comment by TheLearneer** [comment]
Hello @darkbits018, any update?

**Comment by Prabhat147** [comment]
Hello, can I work on this ?

**Comment by TheLearneer** [comment]
Assigned to you, please proceed and write an awesome article @thenishantsapkota ✌️
