### ISSUE TITLE
💻 Update external API links

### ISSUE THREAD

**Issue by TheLearneer** [TheLearneer/api-party#249]
## **Is your feature request related to a problem? Please describe.**
The external links can be improved a bit.

## **Describe the solution you'd like**
It would be great to add the follow to the external API links:
- `ref` query with value **apiParty**
- `external` property to the **NuxtLink** component (<https://v3.nuxtjs.org/api/components/nuxt-link#props>)

## **Describe alternatives you've considered**
N/A

## **Additional context**
In order to add the ref to the links we can use template string from the `href` prop and add `?ref=apiParty` in the prop itself

**Comment by abhijeet007rocks8** [comment]
@TheLearneer Can you shed more light on what you mean in first point of solution:
`ref query with value apiParty`

**Comment by FroostyCodes** [comment]
Hi @TheLearneer 
Can I work on this issue?

**Comment by TheLearneer** [comment]
Sure @FroostyCodes 
Go ahead with it 💪
