### ISSUE TITLE
Write an article about HTTP status code

### ISSUE THREAD

**Issue by TheLearneer** [TheLearneer/api-party#252]
## Is your feature request related to a problem? Please describe.
Write a detailed article about HTTP status code

## Describe the solution you'd like
Explain about:
- Understanding status code
- List out **all** the status codes and give a very short introduction about it. (_maybe use table?_)
- Why they are important
- Porper usage

## Describe alternatives you've considered
N/A

## Additional context
Create a file at https://github.com/TheLearneer/api-party/tree/main/src/content/wiki
Name it `4.http-status-codes` and write the content inside it

Please check https://github.com/TheLearneer/api-party/blob/main/src/content/wiki/1.what-is-api.md to know about some structure that needs to be followed

**Comment by varadtote** [comment]
Assign this is issue to me.
I can write the article considering all rhe points you mentioned

**Comment by thenishantsapkota** [comment]
I'll work on this @TheLearneer

**Comment by TheLearneer** [comment]
> Assign this is issue to me.
> I can write the article considering all the points you mentioned

@varadtote I have assigned another issue to you, please look into it 😄 

---
> I'll work on this

@thenishantsapkota assigning it to you
Make sure to write an awesome article 🙌

**Comment by TheLearneer** [comment]
Completed in #253
