### ISSUE TITLE
🚀 Add information about payment plan

### ISSUE THREAD

**Issue by TheLearneer** [TheLearneer/api-party#266]
## Is your feature request related to a problem? Please describe.
Need to add a feature to mention if the API is entirely free, is entirely paid or has a free as well as paid plan.

## Describe the solution you'd like
The first solution is to add the key `payment` key with the following values:
- free (e.g. Discord)
- paid (e.g. Stripe)
- upgradable (e.g. IP-API)

I guess we might need to add another key for the case when the paid APIs have option of free testing. For e.g. Stripe

## Describe alternatives you've considered
N/A. _Feedbacks are welcome though_

## Additional context
Anyone working on this issue will have to proof-read all the existing API files and add the key-value to those files.
And also update the frontend to display the data properly on the cards.

**Comment by shahGnp** [comment]
I would like to work on this issue.

**Comment by TheLearneer** [comment]
Hi @shahGnp 👋 
I have assigned the issue to you ✌️
