### ISSUE TITLE
(JS-0712) Avoid `target='_blank'` attribute without `rel='noopener noreferrer'`

### ISSUE THREAD

**Issue by TheLearneer** [TheLearneer/api-party#29]
## Description
A malicious actor can gain full control over the user&#x27;s DOM window object. As such, this can lead to phishing attacks such as fake login prompts or password alerts being shown to the user.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/TheLearneer/api-party/issue/JS-0712/occurrences/](https://deepsource.io/gh/TheLearneer/api-party/issue/JS-0712/occurrences/)

**Comment by sambarnes90** [comment]
I would be happy to work on this if you can assign me @TheLearneer?

**Comment by TheLearneer** [comment]
Assigned to you @sambarnes90 😄
